### ISSUE TITLE
Cat Movement Mechanic - Basic Implementation  

### ISSUE THREAD

**Issue by GalWorld** [GalWorld/El-Borondo-de-Tejada#4]
## Description  
Develop the basic movement mechanic for the Cat using low-fidelity cubes or placeholder elements. This task focuses on creating a smooth and responsive walking and running system without incorporating camera controls or jumping mechanics.

## Task  
- Plan and implement the logic for the cat's basic movement (walking and running).  
- Use low-fidelity models or cubes to represent the cat and its interactions with the environment.  
- Ensure the movement feels responsive and natural, adhering to the intended controls.  
- Test the movement mechanic within a simple testing area to validate functionality.

## Goal  
Deliver a functional prototype of the cat's basic walking and running mechanics, ready for integration with more complex features later.

**Comment by PabloH5** [comment]
it is necessary to adjust the camera and create a method for changing camera transform
