### ISSUE TITLE
Free Look Camera Implementation  

### ISSUE THREAD

**Issue by GalWorld** [GalWorld/El-Borondo-de-Tejada#5]
## Description  
Develop and implement a free look camera system to follow the Cat of Tejada. The camera should allow smooth movement, adjustable angles, and a clear view of the environment to enhance gameplay experience.

## Task  
- Implement a **Free Look** camera that follows the player's position dynamically.  
- Allow the player to adjust the camera angle freely using mouse or controller inputs.  
- Ensure smooth transitions and responsiveness to user inputs.  
- Add collision detection to prevent the camera from clipping through objects or terrain.  
- Set limits on camera rotation to avoid awkward or disorienting views.  
- Test the camera functionality in a simple test area to ensure usability and player comfort.

## Optional Features  (under review)
- Implement zoom functionality (if required for gameplay clarity).  
- Add sensitivity settings for user customization.  
- Ensure compatibility with future mechanics like jumping and climbing.

## Goal  
Deliver a functional and responsive free look camera system that enhances the player's control and visibility in the game world.

**Comment by PabloH5** [comment]
![image](https://github.com/user-attachments/assets/c7445d9b-258a-4305-8c28-991600192260)
![image](https://github.com/user-attachments/assets/cecd2321-4a6d-4547-9775-30d6f8abc1b5)
