### ISSUE TITLE
Input System Implementation  

### ISSUE THREAD

**Issue by GalWorld** [GalWorld/El-Borondo-de-Tejada#8]
## Description  
Develop and implement an Input System to handle player controls across multiple input devices, including keyboard, mouse, joystick, and gamepad. The system should be flexible and ready for future updates as needed.

## Task  
- **Movement**:  
  - Keyboard: Support `WASD` and arrow keys for movement.  
  - Joystick and gamepad: Enable movement using analog sticks.  

- **Camera Rotation**:  
  - Mouse: Enable smooth camera rotation with mouse movement.  
  - Joystick and gamepad: Support camera rotation using the right analog stick.  

- **Environment Interaction**:  
  - Keyboard: Map to a designated interaction key (e.g., `E`).  
  - Gamepad: Assign to an appropriate button (e.g., `A` or `X`).  

- **Pause**:  
  - Keyboard: Use `Esc` to trigger and exit the pause menu.  
  - Gamepad: Assign to a designated button (e.g., `Start` or equivalent).  

- **Jump**:  
  - Keyboard: Map to the `Space` key.  
  - Gamepad: Assign to a designated button (e.g., `B` or equivalent).  

- Ensure compatibility across all input devices for seamless gameplay.  
- Test the system thoroughly to confirm that all inputs work as intended across keyboard, mouse, joystick, and gamepad.

## Goal  
Deliver a functional and flexible Input System that handles core game actions across multiple devices and supports future updates.

## Notes  
- This system may require updates as new mechanics or actions are added.  
- Ensure clean integration with other systems like the camera and interaction mechanics.

**Comment by PabloH5** [comment]
![image](https://github.com/user-attachments/assets/9cc4b7ef-c4d4-4604-a3c1-e06ca6ace4a1)

**Comment by GalWorld** [comment]
it is necessary a binding to run, this must be that while it is pressed you can run when you release it you can walk again.
